spring: 
  profiles: 
    active:
    - test
---
server:
 # port: 8201
  port: 3355
spring:
  profiles: dev
  application: 
    name: microservicecloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka
---
server:
  #port: 8202
   port: 3355
spring:
  profiles: test
  application: 
    name: microservicecloud-config-client
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka-test.com:7001/eureka
